version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: desafio_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  seeder:
    build: ./data
    container_name: desafio_seeder
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy

  backend:
    build: ./backend
    container_name: desafio_backend
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy

  graphql:
    build: ./graphql
    container_name: desafio_graphql
    ports:
      - "4000:4000"
    depends_on:
      - backend

  frontend:
    build: ./frontend
    container_name: desafio_frontend
    ports:
      - "3000:5173"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - graphql

volumes:
  postgres-data:
