version: '3.8'

services:
  # Serviço de Banco de Dados (PostgreSQL)
  db:
    image: postgres:14-alpine
    container_name: desafio_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Serviço para popular o banco com dados iniciais
  seeder:
    build: ./data
    container_name: desafio_seeder
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      - db

  # Serviço da API de Backend
  backend:
    build: ./backend
    container_name: desafio_backend
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      - db

  # Serviço da API GraphQL
  graphql:
    build: ./graphql
    container_name: desafio_graphql
    ports:
      - "4000:4000"
    depends_on:
      - backend

  # Serviço do Frontend (React/Vite)
  frontend:
    build: ./frontend
    container_name: desafio_frontend
    ports:
      - "3000:5173"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - graphql

volumes:
  postgres-data:
